homework_10/app/catalog/urls.py
from django.urls import re_path
from . import views

urlpatterns = [
    re_path(r'^$', views.index, name='index'),
    re_path(r'^books/$', views.BookListView.as_view(), name='books'),
    re_path(r'^books/(?P<pk>\d+)$', views.BookDetailView.as_view(), name='book-detail'),
    re_path(r'^authors/$', views.AuthorListView.as_view(), name='authors'),
    re_path(r'^authors/(?P<pk>\d+)$', views.AuthorDetailView.as_view(), name='author-detail'),
    re_path(r'^mybooks/$', views.LoanedBooksByUserListView.as_view(), name='my-borrowed'),
    re_path(r'^book/(?P<pk>[-\w]+)/renew/$',
            views.renew_book_librarian, name='renew-book-librarian'), ]

homework_10/app/library/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = ([
                   path("admin/", admin.site.urls),
                   path('catalog/', include('catalog.urls')),
                   path('accounts/', include('django.contrib.auth.urls')),
                   path('', RedirectView.as_view(url='/catalog/', permanent=True)), ] +
               static(settings.STATIC_URL, document_root=settings.STATIC_ROOT))

homework_10/app/catalog/models.py
import uuid
from datetime import date
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

class Genre(models.Model):
    name = models.CharField(max_length=200, help_text="Введите жанр книги")

    class Meta:
        verbose_name = 'Жанр'
        verbose_name_plural = 'Жанры'

    def __str__(self):
        return self.name

class Book(models.Model):

    class Meta:
        ordering = ['-id']
        verbose_name = 'Книга'
        verbose_name_plural = 'Книги'


    title = models.CharField('Название книги',max_length=200)
    author = models.ForeignKey('Author', on_delete=models.SET_NULL, null=True,
                               verbose_name='Автор')
    summary = models.TextField('Описание книги', max_length=1000,
                               help_text="Введите краткое описание книги")
    isbn = models.CharField('ISBN',max_length=13,
                            help_text='13-ти значный '
                                      '<a href='
                                      '"https://www.isbn-international.org/content/what-isbn">'
                                      'ISBN номер</a>')
    genre = models.ManyToManyField('Genre', help_text="Выберите жанр книги", verbose_name='Жанр')


    def display_genre(self):
        return ', '.join([ genre.name for genre in self.genre.all()[:3] ])
    display_genre.short_description = 'Genre'

    def __str__(self):
        return self.title


    def get_absolute_url(self):
        return reverse('book-detail', args=[str(self.id)])

class BookInstance(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4,
                          help_text="Уникальный ID для книги в библиотеке")
    book = models.ForeignKey('Book', on_delete=models.SET_NULL, null=True, verbose_name='Книга')
    due_back = models.DateField(null=True, blank=True, verbose_name='Возврат:')
    borrower = models.ForeignKey(User, on_delete=models.SET_NULL, null=True,
                                 blank=True, verbose_name='Взял')

    LOAN_STATUS = (
        ('Н', 'Недоступна'),
        ('В', 'Выдана'),
        ('Д', 'Доступна'),
        ('З', 'Зарезервирована'),
    )

    status = models.CharField(max_length=1, choices=LOAN_STATUS, blank=True, default='Д',
                              help_text='Доступность книги', verbose_name='Статус:')

    def is_overdue(self):
        if self.due_back and date.today() > self.due_back:
            return True
        return False
    class Meta:
        ordering = ["due_back"]
        verbose_name = 'Экземпляр книги'
        verbose_name_plural = 'Экземпляры книг'


    def __str__(self):
        return '%s (%s)' % (self.id,self.book.title)

class Author(models.Model):
    first_name = models.CharField('Имя', max_length=100)
    last_name = models.CharField('Фамилия', max_length=100)
    date_of_birth = models.DateField('Дата рождения', null=True, blank=True)
    date_of_death = models.DateField('Дата смерти', null=True, blank=True)

    class Meta:
        ordering = ['last_name',
                    'first_name'
                    ]
        verbose_name = 'Автор'
        verbose_name_plural = 'Авторы'

    def get_absolute_url(self):
        return reverse('author-detail', args=[str(self.id)])


    def __str__(self):
        return '%s, %s' % (self.last_name, self.first_name)

homework_10/app/catalog/forms.py
import datetime
from django import forms
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy


class RenewBookForm(forms.Form):
    renewal_date = forms.DateField(
        help_text="Выберите дату не раньше сегодняшней, и не позже 28 дней.")

    def clean_renewal_date(self):
        data = self.cleaned_data['renewal_date']

        if data < datetime.date.today():
            raise ValidationError(gettext_lazy('Дата раньше сегодняшней!'))

        if data > datetime.date.today() + datetime.timedelta(weeks=4):
            raise ValidationError(gettext_lazy('Дата позже 28 дней!'))

        return data

homework_10/app/catalog/views.py
import datetime
from django.shortcuts import render
from django.views import generic
from django.contrib.auth.decorators import permission_required
from django.shortcuts import get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import RenewBookForm
from .models import Book, Author, BookInstance


def index(request):
    num_books = Book.objects.all().count()
    num_instances = BookInstance.objects.all().count()
    num_instances_available = BookInstance.objects.filter(status__exact='a').count()
    num_authors = Author.objects.count()

    return render(
        request,
        'index.html',
        context={'num_books': num_books,
                 'num_instances': num_instances, 'num_instances_available': num_instances_available,
                 'num_authors': num_authors},
    )


class BookListView(generic.ListView):
    model = Book
    paginate_by = 10


class BookDetailView(generic.DetailView):
    model = Book


class AuthorListView(generic.ListView):
    model = Author
    paginate_by = 10


class AuthorDetailView(generic.DetailView):
    model = Author


class LoanedBooksByUserListView(LoginRequiredMixin, generic.ListView):
    model = BookInstance
    template_name = 'catalog/bookinstance_list_borrowed_user.html'
    paginate_by = 10

    def get_queryset(self):
        return (BookInstance.objects.filter(borrower=self.request.user).
                filter(status__exact='o').order_by('due_back'))


@permission_required('catalog.can_mark_returned')
def renew_book_librarian(request, pk):
    book_inst = get_object_or_404(BookInstance, pk=pk)

    if request.method == 'POST':

        form = RenewBookForm(request.POST)

        if form.is_valid():
            book_inst.due_back = form.cleaned_data['renewal_date']
            book_inst.save()

            return HttpResponseRedirect(reverse('all-borrowed'))

    else:
        proposed_renewal_date = datetime.date.today() + datetime.timedelta(weeks=3)
        form = RenewBookForm(initial={'renewal_date': proposed_renewal_date, })

    return render(request,
                  'catalog/book_renew_librarian.html', {'form': form, 'bookinst': book_inst})

homework_10/app/catalog/templates/base_generic.html
<!doctype html>
<html lang="ru">
  <head>
    {% block title %}<title>Библиотека</title>{% endblock %}
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link
      rel="stylesheet"
      href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>


    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}" />
  </head>

  <body>
    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-2">
          {% block sidebar %}
            {% if user.is_authenticated %}
            <li>Пользователь: {{ user.get_username }}</li>
            <li><a href="{% url 'my-borrowed' %}">Мои книги</a></li>
            <li><a href="{% url 'logout'%}">Выход</a></li>
            {% else %}
            <li><a href="{% url 'login'%}?next={{request.path}}">Вход</a></li>
            {% endif %}
 </ul>
            <ul class="sidebar-nav">
              <li><a href="{% url 'index' %}">Главная</a></li>
              <li><a href="{% url 'books' %}">Все книги</a></li>
              <li><a href="{% url 'authors' %}">Все авторы</a></li>
            </ul>


             </ul>
          {% endblock %}
        </div>
        <div class="col-sm-10 ">{% block content %}{% endblock %}</div>


        {% block pagination %}
          {% if is_paginated %}
            <div class="pagination">
              <span class="page-links">
                {% if page_obj.has_previous %}
                  <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">previous</a>
                {% endif %}
                <span class="page-current">
                  Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                </span>
                {% if page_obj.has_next %}
                  <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">next</a>
                {% endif %}
              </span>
            </div>
          {% endif %}


        {% endblock %}




      </div>
    </div>
  </body>
</html>

homework_10/app/catalog/templates/catalog/author_detail.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Автор: {{ author }} </h1>
<p>{{author.date_of_birth}} - {% if author.date_of_death %}{{author.date_of_death}}{% endif %}</p>

<div style="margin-left:20px;margin-top:20px">
<h4>Книги автора:</h4>

<dl>
{% for book in author.book_set.all %}

  <dt><a href="{% url 'book-detail' book.pk %}">{{book}}</a> ({{book.bookinstance_set.all.count}})</dt>
  <dd>{{book.summary}}</dd>
  {% empty %}
  <p>Нет книг этого автора.</p>
{% endfor %}
</dl>

</div>
{% endblock %}

homework_10/app/catalog/templates/catalog/author_list.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Список авторов:</h1>

{% if author_list %}
  <ul>

  {% for author in author_list %}
    <li>
      <a href="{{ author.get_absolute_url }}">
      {{ author }} ({{author.date_of_birth}} - {% if author.date_of_death %}{{author.date_of_death}}{% endif %})
      </a>
    </li>
  {% endfor %}

 </ul>
{% else %}
  <p>Нет доступных авторов.</p>
{% endif %}
        
        
        
{% endblock %}

homework_10/app/catalog/templates/catalog/book_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Название: {{ book.title }}</h1>

  <p><strong>Автор:</strong> <a href="{% url 'author-detail' book.author.pk %}">{{ book.author }}</a></p>
  <p><strong>Описание:</strong> {{ book.summary }}</p>
  <p><strong>ISBN:</strong> {{ book.isbn }}</p>
  <p><strong>Жанр:</strong> {% for genre in book.genre.all %} {{ genre }}{% if not forloop.last %}, {% endif %}{% endfor %}</p>

  <div style="margin-left:20px;margin-top:20px">
    <h4>Копии:</h4>

    {% for copy in book.bookinstance_set.all %}
    <hr>

    {% if copy.status == 'В' %}
    <p><strong>К возврату до:</strong> {{copy.due_back}}</p>{% endif %}
    <p><strong>Данные:</strong> {{copy.imprint}}</p>
    <p class="text-muted"><strong>Id:</strong> {{copy.id}}</p>
    {% endfor %}
  </div>
{% endblock %}

homework_10/app/catalog/templates/catalog/book_list.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Список книг:</h1>

    {% if book_list %}
    <ul>

      {% for book in book_list %}
      <li>
        <a href="{{ book.get_absolute_url }}"> {{ book.title }}</a> ({{book.author}})
      </li>
      {% endfor %}

    </ul>
    {% else %}
      <p>Нет книг в библиотеке.</p>
    {% endif %}
{% endblock %}

homework_10/app/catalog/templates/catalog/book_renew_librarian.html
{% extends "base_generic.html" %}
{% block content %}

    <h1>Продлить: {{bookinst.book.title}}</h1>
    <p>Взял: {{bookinst.borrower}}</p>
    <p{% if bookinst.is_overdue %} class="text-danger"{% endif %}> До: {{bookinst.due_back}}</p>

    <form action="" method="post">
        {% csrf_token %}
        <table>
        {{ form }}
        </table>
        <input type="submit" value="Продлить" />
    </form>

{% endblock %}

homework_10/app/catalog/templates/catalog/bookinstance_list_borrowed_user.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Взятые мной книги</h1>

    {% if bookinstance_list %}
    <ul>

      {% for bookinst in bookinstance_list %}
      <li class="{% if bookinst.is_overdue %}text-danger{% endif %}">
        <a href="{% url 'book-detail' bookinst.book.pk %}">{{bookinst.book.title}}</a> ({{ bookinst.due_back }})
      </li>
      {% endfor %}
    </ul>

    {% else %}
      <p>Нет книг.</p>
    {% endif %}
{% endblock %}

homework_10/app/catalog/templates/index.html
{% extends "base_generic.html" %}

{% block content %}
<h1>Библиотека</h1>

  <p>Добро пожаловать в <strong>Библиотеку</strong>, проектную работу для <a href="https://www.otus.ru"> OTUS</a>.</p>

  <p>В библиотеке имеется следующее количество записей:</p>
  <ul>
    <li><strong>Книги:</strong> {{ num_books }}</li>
    <li><strong>Копии:</strong> {{ num_instances }}</li>
    <li><strong>Доступное количество книг:</strong> {{ num_instances_available }}</li>
    <li><strong>Авторы:</strong> {{ num_authors }}</li>
  </ul>

{% endblock %}