homework_06/blog/models/__init__.py
__all__ = (
    "User",
    "Post",
)

from .user import User
from .post import Post

homework_06/blog/models/database.py
from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()

homework_06/blog/models/post.py
from sqlalchemy import (
    Column,
    Integer,
    String,
    ForeignKey
)
from sqlalchemy.orm import relationship

from .database import db


class Post(db.Model):
    __tablename__ = "posts"
    id = Column(Integer, primary_key=True)
    user_id = Column(Integer, ForeignKey("users.id"), nullable=False, unique=False)
    title = Column(String(100), nullable=False, unique=True)
    body = Column(String(500), nullable=False, unique=False)

    user = relationship("User", back_populates="posts")

homework_06/blog/models/user.py
from sqlalchemy import (
    Column,
    String,
    Integer
)
from sqlalchemy.orm import relationship

from .database import db


class User(db.Model):
    __tablename__ = "users"
    id = Column(Integer, primary_key=True)
    name = Column(String(50), nullable=False, unique=False)
    username = Column(String(20), nullable=False, unique=True)
    email = Column(String(30), nullable=False, unique=True)

    posts = relationship("Post", back_populates="user")

homework_06/blog/views/forms/__init__.py
__all__ = "PostForm", "UserForm"

from .new_post import PostForm
from .new_user import UserForm

homework_06/blog/views/forms/new_post.py
from flask_wtf import FlaskForm
from wtforms import StringField
from wtforms.validators import DataRequired


class PostForm(FlaskForm):
    user = StringField(
        label="Username",
        name="username",
        validators=[DataRequired()]
    )
    title = StringField(
        label="Title",
        name="title",
        validators=[DataRequired()]
    )
    body = StringField(
        label="Post",
        name="body",
        validators=[DataRequired()]
    )

homework_06/blog/views/forms/new_user.py
from flask_wtf import FlaskForm
from wtforms import StringField
from wtforms.validators import DataRequired


class UserForm(FlaskForm):
    name = StringField(
        label="Name",
        name="name",
        validators=[DataRequired()]
    )
    username = StringField(
        label="Username",
        name="username",
        validators=[DataRequired()]
    )
    email = StringField(
        label="E-mail",
        name="email",
        validators=[DataRequired()]
    )

homework_06/blog/app.py
from flask import Flask, render_template
from flask_migrate import Migrate

from views import posts_app
from views import users_app
from models import Post
from models.database import db


app = Flask(__name__)
app.config.from_pyfile('settings.py')
db.init_app(app)
migrate = Migrate(app, db, compare_type=True)

app.register_blueprint(posts_app, url_prefix="/posts")
app.register_blueprint(users_app, url_prefix="/users")


@app.route("/", endpoint="view_blog")
def view_blog():
    posts = Post.query.all()
    return render_template("view_blog.html", posts=posts)


if __name__ == "__main__":
    app.run(port=8000)

homework_06/blog/views/__init__.py
__all__ = "users_app", "posts_app"

from .users import users_app
from .posts import posts_app

homework_06/blog/views/posts.py
from flask import (
    Blueprint,
    render_template,
    request,
    redirect,
    url_for,
)
from sqlalchemy.exc import IntegrityError, DatabaseError
from werkzeug.exceptions import InternalServerError

from models import User, Post
from views.forms import PostForm
from models.database import db


posts_app = Blueprint("posts_app", __name__)


@posts_app.route("/add/", methods=["GET", "POST"], endpoint="add_post")
def add_post():
    form = PostForm()
    if request.method == "GET":
        return render_template("posts/add_post.html", form=form)

    if not form.validate_on_submit():
        return render_template("posts/add_post.html", form=form), 400

    user = form.user.data
    title = form.title.data
    body = form.body.data

    user_obj = User.query.filter_by(username=user).first()

    if not user_obj:
        return f"User {user} not found in the database", 500

    post = Post(user=user_obj, title=title, body=body)
    db.session.add(post)

    try:
        db.session.commit()
    except IntegrityError:
        error_text = f"Could not create post {post.title!r}"
        form.form_errors.append(error_text)
        return render_template("posts/add_post.html", form=form), 400

    except DatabaseError:
        raise InternalServerError(f"Could not create post {post.title!r}")

    url = url_for("view_blog")
    return redirect(url)

homework_06/blog/views/users.py
from flask import (
    Blueprint,
    render_template,
    request,
    flash,
    redirect,
    url_for
)
from sqlalchemy.exc import IntegrityError, DatabaseError
from werkzeug.exceptions import InternalServerError

from models import User, Post
from views.forms import UserForm
from models.database import db


users_app = Blueprint("users_app", __name__)


@users_app.route("/add/", methods=["GET", "POST"], endpoint="add_user")
def add_user():
    form = UserForm()
    if request.method == "GET":
        return render_template("users/add_user.html", form=form)

    if not form.validate_on_submit():
        return render_template("users/add_user.html", form=form), 400

    name = form.name.data
    username = form.username.data
    email = form.email.data

    user = User(name=name, username=username, email=email)
    db.session.add(user)

    try:
        db.session.commit()
    except IntegrityError:
        error_text = f"Could not add user {user.username!r}"
        form.form_errors.append(error_text)
        return render_template("users/add_user.html", form=form), 400

    except DatabaseError:
        raise InternalServerError(f"Could not create post {user.username!r}")

    flash(f"User {username} ({name}) is created", "success")
    url = url_for("users_app.add_user")
    return redirect(url)

homework_06/blog/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="{{ url_for('static', filename='css/bootstrap.min.css') }}" rel="stylesheet">
    <title>
        {% block title %}
            Base Title
        {% endblock %}
    </title>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
        <a class="navbar-brand" href="#">Blog</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item">
                {% set view_blog_path = url_for("view_blog") %}
              <a class="nav-link {{ 'active' if request.path == view_blog_path else '' }} " aria-current="page" href="{{ view_blog_path }}">View blog</a>
            </li>
            <li class="nav-item">
                {% set add_post_path = url_for("posts_app.add_post") %}
              <a class="nav-link {{ 'active' if request.path == add_post_path else '' }}" href="{{ add_post_path }}">Add post</a>
            </li>
            <li class="nav-item">
                {% set add_user_path = url_for("users_app.add_user") %}
              <a class="nav-link {{ 'active' if request.path == add_user_path else '' }}" href="{{ add_user_path }}">Add user</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    {% block body %}
        Base body
    {% endblock %}

    <script src={{ url_for('static', filename='js/bootstrap.bundle.min.js') }}></script>
</body>

</html>

homework_06/blog/templates/blog.html
{% extends 'base.html' %}

{% block body %}
    <div class="container-fluid">
    {% if posts %}
        {% for post in posts %}
        <div class="accordion" id="accordionBlog">
          <div class="accordion-item">
            <h2 class="accordion-header">
              <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapse_{{ post.id }}" aria-expanded="true" aria-controls="collapse_{{ post.id }}">
                  {{ post.title }}
              </button>
            </h2>
            <div id="collapse_{{ post.id }}" class="accordion-collapse collapse show" aria-labelledby="heading_{{ post.id }}" data-bs-parent="#accordionBlog">
              <div class="accordion-body">
                  {{ post.body }}
              </div>
            </div>
          </div>
        </div>
        {% endfor %}
    {% else %}
        <div><strong>No posts exist</strong></div>
    {% endif %}
    </div>
{% endblock %}

{% block title %}
  Blog
{% endblock %}

homework_06/blog/templates/posts/post.html
{% extends 'base.html' %}


{% block body %}
    <div class="container-fluid">
    <div class="col-4">
        <h1>Add post</h1>
          <form method="post">

            {{ form.hidden_tag() }}

            {{ form.user.label(class="form-label") }}
            {{ form.user(class="form-control") }}

            {{ form.title.label(class="form-label") }}
            {{ form.title(class="form-control") }}

            {{ form.body.label(class="form-label") }}
            {{ form.body(class="form-control") }}

            {% if form.errors %}
              <div class="errors my-2">
                {% for name, errors in form.errors.items() %}
                  <div class="alert alert-danger">
                    {% if name %}
                      <strong>{{ name }}</strong>
                    {% endif %}
                    <ul>
                      {% for error in errors %}
                        <li>{{ error }}</li>
                      {% endfor %}
                    </ul>
                  </div>
                {% endfor %}
              </div>
            {% endif %}

            <button type="submit" class="btn btn-primary my-2">Create post</button>
          </form>
    </div>
    </div>
{% endblock %}


{% block title %}
  Add post
{% endblock %}

homework_06/blog/templates/users/user.html
{% extends 'base.html' %}


{% block body %}
    <div class="container-fluid">
    <div class="col-4">
        <h1>Add user</h1>
          <form method="post">

            {{ form.hidden_tag() }}

            {{ form.name.label(class="form-label") }}
            {{ form.name(class="form-control") }}

            {{ form.username.label(class="form-label") }}
            {{ form.username(class="form-control") }}

            {{ form.email.label(class="form-label") }}
            {{ form.email(class="form-control") }}

            {% if form.errors %}
              <div class="errors my-2">
                {% for name, errors in form.errors.items() %}
                  <div class="alert alert-danger">
                    {% if name %}
                      <strong>{{ name }}</strong>
                    {% endif %}
                    <ul>
                      {% for error in errors %}
                        <li>{{ error }}</li>
                      {% endfor %}
                    </ul>
                  </div>
                {% endfor %}
              </div>
            {% endif %}

            <button type="submit" class="btn btn-primary my-2">Create user</button>
          </form>
    </div>
    </div>
{% endblock %}


{% block title %}
  Add user
{% endblock %}